# Generated by Django 5.2.7 on 2026-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieApp', '0003_userprofile_role_alter_dailyconsumption_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyconsumption',
            name='quantity',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
